# Array Creation & Initialization

In [1]:
import numpy as np

# 3x3 Identity matrix
identity_matrix = np.eye(3)

# 1D array with integers from 1 to 9
arr = np.arange(1, 10)

print("Identity Matrix:\n", identity_matrix)
print("1D Array:", arr)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1D Array: [1 2 3 4 5 6 7 8 9]


# Element-wise Operations on Arrays

In [2]:
# Account balances in two months
account_month1 = np.array([1000, 1500, 2000, 500])
account_month2 = np.array([1200, 1600, 2100, 550])

# Add the two months to get the total balances
total_balances = account_month1 + account_month2

# Calculate the monthly growth percentage
growth = ((account_month2 - account_month1) / account_month1) * 100

print("Total Balances:", total_balances)
print("Growth Percentage:", growth)


Total Balances: [2200 3100 4100 1050]
Growth Percentage: [20.          6.66666667  5.         10.        ]


# Filtering and Conditional Operations

In [3]:
# Array of daily temperatures
temperatures = np.array([25, 30, 35, 28, 40, 22, 33])

# Filter out temperatures above 30°C
hot_days = temperatures[temperatures > 30]

print("Days with temperatures above 30°C:", hot_days)


Days with temperatures above 30°C: [35 40 33]


#  Data Reshaping

In [4]:
# Scores of 6 students in 3 subjects
scores = np.array([85, 90, 78, 88, 92, 81, 95, 87, 89, 80, 85, 86])

# Reshape the 1D array into a 2D array of 4x3 (4 students, 3 subjects)
reshaped_scores = scores.reshape(4, 3)

print("Reshaped Scores Matrix:\n", reshaped_scores)


Reshaped Scores Matrix:
 [[85 90 78]
 [88 92 81]
 [95 87 89]
 [80 85 86]]


# Statistical Operations

In [5]:
# Sales data for a product over 12 months
sales = np.array([150, 200, 250, 180, 220, 300, 270, 320, 310, 400, 390, 500])

# Calculate statistical measures
mean_sales = np.mean(sales)
median_sales = np.median(sales)
std_dev_sales = np.std(sales)

print(f"Mean Sales: {mean_sales}")
print(f"Median Sales: {median_sales}")
print(f"Standard Deviation of Sales: {std_dev_sales}")


Mean Sales: 290.8333333333333
Median Sales: 285.0
Standard Deviation of Sales: 97.59254866820292


# Matrix Multiplication for Data Transformation

In [6]:
# Point in 2D space
point = np.array([2, 3])

# Rotation matrix (for rotating 90 degrees counterclockwise)
rotation_matrix = np.array([[0, -1], [1, 0]])

# Perform matrix multiplication (dot product)
rotated_point = np.dot(rotation_matrix, point)

print("Rotated Point:", rotated_point)


Rotated Point: [-3  2]


## Solving Linear Equations
Problem: Solve a system of linear equations. For example:

2
𝑥
+
3
𝑦
=
5
2x+3y=5
4
𝑥
+
𝑦
=
6
4x+y=6

In [7]:
# Coefficients of the equations
A = np.array([[2, 3], [4, 1]])

# Constants on the right-hand side of the equations
B = np.array([5, 6])

# Solving for x and y
solution = np.linalg.solve(A, B)

print("Solution (x, y):", solution)


Solution (x, y): [1.3 0.8]


# Working with Random Numbers

In [8]:
# Simulate 1000 rolls of a fair die (values from 1 to 6)
rolls = np.random.randint(1, 7, size=1000)

# Calculate the frequency of each die face
frequencies = np.bincount(rolls)[1:]  # Exclude zero (index 0)

# Calculate probabilities
probabilities = frequencies / 1000

print("Probabilities of each die face:", probabilities)


Probabilities of each die face: [0.158 0.156 0.177 0.176 0.164 0.169]


# Data Aggregation

In [9]:
# Sales data (4 stores and 3 months)
sales_data = np.array([[200, 220, 250],
                       [300, 310, 320],
                       [150, 180, 190],
                       [400, 430, 410]])

# Sum sales across columns for each store
total_sales_per_store = np.sum(sales_data, axis=1)

print("Total sales for each store:", total_sales_per_store)


Total sales for each store: [ 670  930  520 1240]


# Sorting & Searching

In [10]:
# Array of student grades
grades = np.array([88, 92, 79, 85, 94, 76, 90])

# Sort the grades
sorted_grades = np.sort(grades)

# Find the position of grade 85
position = np.where(grades == 85)

print("Sorted Grades:", sorted_grades)
print("Position of grade 85:", position)


Sorted Grades: [76 79 85 88 90 92 94]
Position of grade 85: (array([3]),)
